
[build]
# Install PHP and JS dependencies, then build assets and clear config cache
command = "composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan config:clear"

[deploy]
# Run migrations and seeders after deploy
dependsOn = ["build"]
command = "php artisan storage:link --force && php artisan migrate --force --seed"

[start]
# Run migrations, seeders and start the server
command = "php artisan migrate --force --seed && php -S 0.0.0.0:$PORT -t public"