
[build]
# Install PHP and JS dependencies, then build assets and clear config cache
command = "composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan config:clear"

[deploy]
# Run migrations after deploy
dependsOn = ["build"]
command = "php artisan storage:link --force && php artisan migrate --force"

[start]
command = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"