[build]
command = "composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan config:clear"

[deploy]
dependsOn = ["build"]
command = "php artisan storage:link --force && php artisan migrate --force --seed"

[start]
command = "php -S 0.0.0.0:$PORT -t public"